  cat > docker-compose.prod.yml <<'YML'
  version: "3.8"

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: myapp_app
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      ports:
        - "8000:8000"
      depends_on:
        - db
      command: >
        sh -lc "
          cd /var/www/html &&
          composer install --no-interaction --prefer-dist --no-progress || true &&
          cd src &&
          php artisan key:generate --force &&
          php artisan migrate --force &&
          php artisan serve --host=0.0.0.0 --port=8000
        "

    db:
      image: mysql:8.0
      container_name: myapp_db
      restart: always
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: laravel
        MYSQL_PASSWORD: root
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"

  volumes:
    db_data:
    YML