name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Проверяем, что docker-compose читается
      - name: Validate compose file
        run: docker compose -f docker-compose.yml config -q

      # Самое простое: просто собираем образы (без запуска)
      - name: Build images
        run: docker compose -f docker-compose.yml build
